=== politecnicoProyect2022/XML_Ejercicio6/exercise6.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="listacursos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="curso" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="alumno" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="DNI" type="xs:integer" />
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="apellido" type="xs:string" />
                                        <xs:element name="segundoApellido" type="xs:string" minOccurs="0" />
                                        <xs:element name="listaAsignaturas">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="asignatura" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre" type="xs:string" />
                                                                <xs:element name="profesor">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="NRP" type="xs:string" />
                                                                            <xs:element name="nombre" type="xs:string" />
                                                                            <xs:element name="apellido" type="xs:string" />
                                                                            <xs:element name="segundoApellido" type="xs:string" minOccurs="0"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="codigo" type="xs:integer" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== politecnicoProyect2022/XML_Ejercicio6/exercise6.xml
<?xml version="1.0" encoding="UTF-8"?>
<listacursos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="exercise6.xsd">
<!--DOCTYPE listacursos SYSTEM "exercise6.dtd">

<listacursos-->
    <curso>
        <alumno>
            <DNI>734674</DNI>
            <nombre>Ejemplo Nombre</nombre>
            <apellido>Ejemplo apellido</apellido>
            <listaAsignaturas>
                <asignatura codigo="5684">
                    <nombre>Matematicas</nombre>
                    <profesor>
                        <NRP>345673</NRP>
                        <nombre>Mario</nombre>
                        <apellido>Ortega</apellido>
                        <segundoApellido>Salazar</segundoApellido>
                    </profesor>
                </asignatura>
                <asignatura codigo="5674">
                    <nombre>Quimica</nombre>
                    <profesor>
                        <NRP>34673</NRP>
                        <nombre>Sergio</nombre>
                        <apellido>Ortega</apellido>
                    </profesor>
                </asignatura>
            </listaAsignaturas>
        </alumno>
    </curso>
</listacursos>
